<h1>Create NumPy arrays using Python's "array like" data types</h1>


In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.13.3


In [3]:
my_list = [-17, 0, 5, 4, 3, 1]
my_array_from_list = np.array(my_list)
my_array_from_list

array([-17,   0,   5,   4,   3,   1])

In [4]:
my_array_from_list * 5

array([-85,   0,  25,  20,  15,   5])

In [5]:
my_tuple = (-8, 0, 0.35, 5+7j)
np.array(my_tuple)

array([-8.00+0.j,  0.00+0.j,  0.35+0.j,  5.00+7.j])

### differences between python & numpy data structures 

In [6]:
my_tuple *6 

(-8,
 0,
 0.35,
 (5+7j),
 -8,
 0,
 0.35,
 (5+7j),
 -8,
 0,
 0.35,
 (5+7j),
 -8,
 0,
 0.35,
 (5+7j),
 -8,
 0,
 0.35,
 (5+7j),
 -8,
 0,
 0.35,
 (5+7j))

In [7]:
np.array(my_tuple) * 6

array([-48.0 +0.j,   0.0 +0.j,   2.1 +0.j,  30.0+42.j])