<h1>linspace(), zeros(), ones(), and NumPy data types</h1>

In [1]:
import numpy as np

In [1]:
np.linspace(5, 15, 9)np.

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
np.linspace(6, 18, 9)

array([  6. ,   7.5,   9. ,  10.5,  12. ,  13.5,  15. ,  16.5,  18. ])

In [5]:
my_linspace = np.linspace(5, 15, 9, retstep=True)

In [6]:
my_linspace

(array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ,  11.25,  12.5 ,  13.75,  15.  ]),
 1.25)

In [7]:
my_linspace = np.linspace(6, 18, 9, retstep=True)

In [8]:
my_linspace

(array([  6. ,   7.5,   9. ,  10.5,  12. ,  13.5,  15. ,  16.5,  18. ]), 1.5)

## Numpy zero()function 

In [10]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [11]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [13]:
np.zeros((5,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [14]:
np.ones((5, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [15]:
np.zeros((5, 4, 3))

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [16]:
np.zeros(11)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [17]:
np.zeros(11, dtype='int32')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.zeros(11, dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)